/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

// Escribir una interface perimetrable con un método calcularPerimetro()
// Interface Perimetrable
interface Perimetrable {
    fun calcularPerimetro(): Double
}

// Clase Coche
class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

// Escribir una clase Rectangulo que implemente la interface Perimetrable
// Clase Rectangulo
    class Rectangulo(val base: Double, val altura: Double) : Perimetrable {
        override fun calcularPerimetro(): Double = 2 * (base + altura)
        override fun toString(): String = "Rectángulo(base=$base, altura=$altura)"
    }

// Escribir una clase Circulo que implemente la interface Perimetrable
// Clase Circulo
class Circulo(val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double = 2 * Math.PI * radio
    override fun toString(): String = "Círculo(radio=$radio)"
}

fun main() {

    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")

    // Crear una lista con un objeto de cada clase y mostrar el perímetro de cada uno
    // Lista y mostrar perímetros
    val figuras: List<Perimetrable> = listOf(
        Rectangulo(4.0, 3.0),
        Circulo(2.0)
    )
    for (figura in figuras) {
        println("${figura}: perímetro = ${figura.calcularPerimetro()}")
    }
}